apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: openshift-gitops
spec:
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.45.8
    helm:
      values: |
        namespaceOverride: "argo-workflows"
        workflow:
          serviceAccount:
            create: true
            name: "argo-workflow"
          rbac:
            create: true
        controller:
          workflowNamespaces:
            - argo-workflows
  destination:
    name: in-cluster
    createNamespace: true
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
