apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-infra-config-workload
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: default
  source:
    directory:
      recurse: true
    path: workload
    repoURL: https://github.com/stolostron/shared-infra-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
