kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcm-delivery-namespace-access
  namespace: hcm-delivery
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: hcm-delivery
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:hcm-delivery'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
