kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: collective-cluster-admins
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: shared-infrastructure-admins
  - kind: ServiceAccount
    name: gurnben
    namespace: cicd
  - kind: ServiceAccount
    name: gurnben
    namespace: managed-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
