apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: console-squad-public-issuer
  namespace: cert-manager
spec:
  acme:
    email: acm-cicd@redhat.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: haproxy
      selector:
        matchLabels:
          use-http01-solver: "true"
    - dns01:
        cnameStrategy: Follow
        route53:
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: console-aws-creds
          region: us-east-1
          hostedZoneID: Z353L7N3UKR0RN
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: console-aws-creds
      selector:
        matchLabels:
          use-dns01-solver: "true"